# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'FujiSDK-Test' do
    
    pre_install do |installer|
        def installer.verify_no_static_framework_transitive_dependencies; end
    end

  # Pods for FujiSDK-Test
  
  pod 'FujiSDK', :path => '../FujiSDK'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

end
